[package]
name = "sdcore"
version = "0.1.0"
description = "Virtual distributed filesystem engine that powers Spacedrive."
authors = ["Spacedrive Technology Inc."]
license = "GNU GENERAL PUBLIC LICENSE"
repository = "https://github.com/spacedriveapp/spacedrive"
edition = "2021"
rust-version = "1.63.0"

[features]
default = ["p2p"]
p2p = [] # This feature controlls whether the Spacedrive Core contains the Peer to Peer syncing engine (It isn't required for the hosted core so we can disable it).
mobile = [] # This feature allows features to be disabled when the Core is running on mobile.
ffmpeg = ["dep:ffmpeg-next"] # This feature controls whether the Spacedrive Core contains functionality which requires FFmpeg.

[dependencies]
hostname = "0.3.1"

# Universal Dependencies
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
serde_json = "1.0"
futures = "0.3"
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
int-enum = "0.4.0"
rmp = "^0.8.11"
rmp-serde = "^1.1.0"

# Project dependencies
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", tag = "0.6.0", features = [
  "rspc",
  "sqlite-create-many",
] }
quaint = { git = "https://github.com/prisma/quaint.git", features = ["sqlite", "uuid"] }
migration-core = { git = "https://github.com/Brendonovich/prisma-engines.git" }
sql-migration-connector = { git = "https://github.com/Brendonovich/prisma-engines.git" }
rspc = { version = "0.0.4", features = ["uuid", "chrono", "tracing"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
sysinfo = "0.23.9"
thiserror = "1.0.30"

tokio = { version = "1.17.0", features = ["sync", "rt-multi-thread"] }
include_dir = { version = "0.7.2", features = ["glob"] }
async-trait = "^0.1.52"
image = "0.24.1"
webp = "0.2.2"
ffmpeg-next = { version = "5.0.3", optional = true, features = [] }
fs_extra = "1.2.0"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
async-stream = "0.3.3"
once_cell = "1.13.0"
ctor = "0.1.22"
globset = { version = "^0.4.9", features = ["serde1"] }
itertools = "^0.10.3"
enumflags2 = "0.7.5"

[dev-dependencies]
tempfile = "^3.3.0"
tracing-test = "^0.2.3"